strategy = {
  "2": {
    "hard": {
      "17": "Stand",
      "16": "Stand",
      "15": "Stand",
      "14": "Stand",
      "13": "Stand",
      "12": "Hit",
      "11": "Double",
      "10": "Double",
      "9": "Hit",
      "8": "Hit"
    },
    "soft": {
        "19": "Stand",
        "18": "Stand",
        "17": "Hit",
        "16": "Hit",
        "15": "Hit",
        "14": "Hit",
        "13": "Hit",
    },
    "split": {
      "A": "Split",
      "8": "Split",
      "10": "Stand",
      "9": "Split",
      "7": "Split",
      "6": "Split",
      "5": "Double",
      "4": "Hit",
      "3": "Split",
      "2": "Split"
    },
  },
  "3": {
    "hard": {
      "17": "Stand",
      "16": "Stand",
      "15": "Stand",
      "14": "Stand",
      "13": "Stand",
      "12": "Hit",
      "11": "Double",
      "10": "Double",
      "9": "Double",
      "8": "Hit"
    },
    "soft": {
        "19": "Stand",
        "18": "Double",
        "17": "Double",
        "16": "Hit",
        "15": "Hit",
        "14": "Hit",
        "13": "Hit",
    },
    "split": {
      "A": "Split",
      "8": "Split",
      "10": "Stand",
      "9": "Split",
      "7": "Split",
      "6": "Split",
      "5": "Double",
      "4": "Hit",
      "3": "Split",
      "2": "Split"
    },
  },
  "4": {
    "hard": {
      "17": "Stand",
      "16": "Stand",
      "15": "Stand",
      "14": "Stand",
      "13": "Stand",
      "12": "Stand",
      "11": "Double",
      "10": "Double",
      "9": "Double",
      "8": "Hit"
    },
    "soft": {
        "19": "Stand",
        "18": "Double",
        "17": "Double",
        "16": "Double",
        "15": "Double",
        "14": "Hit",
        "13": "Hit",
    },
    "split": {
      "A": "Split",
      "8": "Split",
      "10": "Stand",
      "9": "Split",
      "7": "Split",
      "6": "Split",
      "5": "Double",
      "4": "Hit",
      "3": "Split",
      "2": "Split"
    },
  },
   "5": {
    "hard": {
      "17": "Stand",
      "16": "Stand",
      "15": "Stand",
      "14": "Stand",
      "13": "Stand",
      "12": "Stand",
      "11": "Double",
      "10": "Double",
      "9": "Double",
      "8": "Hit"
    },
    "soft": {
        "19": "Stand",
        "18": "Double",
        "17": "Double",
        "16": "Double",
        "15": "Double",
        "14": "Double",
        "13": "Double",
    },
    "split": {
      "A": "Split",
      "8": "Split",
      "10": "Stand",
      "9": "Split",
      "7": "Split",
      "6": "Split",
      "5": "Double",
      "4": "Split",
      "3": "Split",
      "2": "Split"
    },
  },
  "6": {
    "hard": {
      "17": "Stand",
      "16": "Stand",
      "15": "Stand",
      "14": "Stand",
      "13": "Stand",
      "12": "Stand",
      "11": "Double",
      "10": "Double",
      "9": "Double",
      "8": "Hit"
    },
    "soft": {
        "19": "Stand",
        "18": "Double",
        "17": "Double",
        "16": "Double",
        "15": "Double",
        "14": "Double",
        "13": "Double",
    },
    "split": {
      "A": "Split",
      "8": "Split",
      "10": "Stand",
      "9": "Split",
      "7": "Split",
      "6": "Split",
      "5": "Double",
      "4": "Split",
      "3": "Split",
      "2": "Split"
    },
  },
  "7": {
    "hard": {
      "17": "Stand",
      "16": "Hit",
      "15": "Hit",
      "14": "Hit",
      "13": "Hit",
      "12": "Hit",
      "11": "Double",
      "10": "Double",
      "9": "Hit",
      "8": "Hit"
    },
    "soft": {
        "19": "Stand",
        "18": "Stand",
        "17": "Hit",
        "16": "Hit",
        "15": "Hit",
        "14": "Hit",
        "13": "Hit",
    },
    "split": {
      "A": "Split",
      "8": "Split",
      "10": "Stand",
      "9": "Stand",
      "7": "Split",
      "6": "Hit",
      "5": "Double",
      "4": "Hit",
      "3": "Split",
      "2": "Split"
    },
  },
  "8": {
    "hard": {
      "17": "Stand",
      "16": "Hit",
      "15": "Hit",
      "14": "Hit",
      "13": "Hit",
      "12": "Hit",
      "11": "Double",
      "10": "Double",
      "9": "Hit",
      "8": "Hit"
    },
    "soft": {
        "19": "Stand",
        "18": "Stand",
        "17": "Hit",
        "16": "Hit",
        "15": "Hit",
        "14": "Hit",
        "13": "Hit",
    },
    "split": {
      "A": "Split",
      "8": "Split",
      "10": "Stand",
      "9": "Split",
      "7": "Hit",
      "6": "Hit",
      "5": "Double",
      "4": "Hit",
      "3": "Hit",
      "2": "Hit"
    },
  },
  "9": {
    "hard": {
      "17": "Stand",
      "16": "Hit",
      "15": "Hit",
      "14": "Hit",
      "13": "Hit",
      "12": "Hit",
      "11": "Double",
      "10": "Double",
      "9": "Hit",
      "8": "Hit"
    },
    "soft": {
        "19": "Stand",
        "18": "Hit",
        "17": "Hit",
        "16": "Hit",
        "15": "Hit",
        "14": "Hit",
        "13": "Hit",
    },
    "split": {
      "A": "Split",
      "8": "Split",
      "10": "Stand",
      "9": "Split",
      "7": "Hit",
      "6": "Hit",
      "5": "Double",
      "4": "Hit",
      "3": "Hit",
      "2": "Hit"
    },
  },
  "10": {
    "hard": {
      "17": "Stand",
      "16": "Hit",
      "15": "Hit",
      "14": "Hit",
      "13": "Hit",
      "12": "Hit",
      "11": "Double",
      "10": "Hit",
      "9": "Hit",
      "8": "Hit"
    },
    "soft": {
        "19": "Stand",
        "18": "Hit",
        "17": "Hit",
        "16": "Hit",
        "15": "Hit",
        "14": "Hit",
        "13": "Hit",
    },
    "split": {
      "A": "Split",
      "8": "Split",
      "10": "Stand",
      "9": "Split",
      "7": "Hit",
      "6": "Hit",
      "5": "Hit",
      "4": "Hit",
      "3": "Hit",
      "2": "Hit"
    },
  },
  "A": {
    "hard": {
      "17": "Stand",
      "16": "Hit",
      "15": "Hit",
      "14": "Hit",
      "13": "Hit",
      "12": "Hit",
      "11": "Hit",
      "10": "Hit",
      "9": "Hit",
      "8": "Hit"
    },
    "soft": {
        "19": "Stand",
        "18": "Hit",
        "17": "Hit",
        "16": "Hit",
        "15": "Hit",
        "14": "Hit",
        "13": "Hit",
    },
    "split": {
      "A": "Split",
      "8": "Split",
      "10": "Stand",
      "9": "Split",
      "7": "Hit",
      "6": "Hit",
      "5": "Hit",
      "4": "Hit",
      "3": "Hit",
      "2": "Hit"
    },
  },
}